### ISSUE TITLE
Tests won't run in IDE (in-browser or desktop)

### ISSUE THREAD

**Issue by ivalentine** [learn-co-curriculum/git-basics-lab#5]
Running `learn` in both the in-browser and desktop IDE results in the following error message:

```
/home/bionic-template-4026/git-basics-lab-online-web-sp-000/node_modules/mocha/lib/reporters/base.js:300
  runner.stats = stats;
               ^

TypeError: Cannot set property stats of #<EventEmitter> which has only a getter
    at Spec.Base (/home/bionic-template-4026/git-basics-lab-online-web-sp-000/node_modules/mocha/lib/reporters/base.js:300:16)
    at new Spec (/home/bionic-template-4026/git-basics-lab-online-web-sp-000/node_modules/mocha/lib/reporters/spec.js:30:8)
    at withReplacedStdout (/home/bionic-template-4026/git-basics-lab-online-web-sp-000/node_modules/mocha-multi/mocha-multi.js:220:21)
    at withReplacedStdout (/home/bionic-template-4026/git-basics-lab-online-web-sp-000/node_modules/mocha-multi/mocha-multi.js:146:12)
    at setup.map (/home/bionic-template-4026/git-basics-lab-online-web-sp-000/node_modules/mocha-multi/mocha-multi.js:216:14)
    at Array.map (<anonymous>)
    at initReportersAndStreams (/home/bionic-template-4026/git-basics-lab-online-web-sp-000/node_modules/mocha-multi/mocha-multi.js:208:6)
    at mochaMulti (/home/bionic-template-4026/git-basics-lab-online-web-sp-000/node_modules/mocha-multi/mocha-multi.js:267:31)
    at new MochaMulti (/home/bionic-template-4026/git-basics-lab-online-web-sp-000/node_modules/mocha-multi/mocha-multi.js:293:25)
    at Mocha.run (/home/bionic-template-4026/git-basics-lab-online-web-sp-000/node_modules/mocha/lib/mocha.js:582:18)
    at Object.<anonymous> (/home/bionic-template-4026/git-basics-lab-online-web-sp-000/node_modules/mocha/bin/_mocha:637:18)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3
[18:44:08] ((HEAD detached at 7114f63)) git-basics-lab-online-web-sp-000
// ♥ Traceback (most recent call last):
        11: from /usr/local/rvm/gems/ruby-2.6.1/bin/ruby_executable_hooks:24:in&#96;<main>'
        10: from /usr/local/rvm/gems/ruby-2.6.1/bin/ruby_executable_hooks:24:in&#96;eval'
         9: from /usr/local/rvm/gems/ruby-2.6.1/bin/learn-test:23:in &#96;<main>'
         8: from /usr/local/rvm/gems/ruby-2.6.1/bin/learn-test:23:in &#96;load'
         7: from /usr/local/rvm/gems/ruby-2.6.1/gems/learn-test-2.6.1/bin/learn-test:68:in &#96;<top (required)>'
         6: from /usr/local/rvm/gems/ruby-2.6.1/gems/learn-test-2.6.1/lib/learn_test/runner.rb:20:in &#96;run'
         5: from /usr/local/rvm/gems/ruby-2.6.1/gems/learn-test-2.6.1/lib/learn_test/runner.rb:20:in &#96;fork'
         4: from /usr/local/rvm/gems/ruby-2.6.1/gems/learn-test-2.6.1/lib/learn_test/runner.rb:21:in &#96;block in run'
         3: from /usr/local/rvm/gems/ruby-2.6.1/gems/learn-test-2.6.1/lib/learn_test/runner.rb:44:in &#96;report_and_clean'
         2: from /usr/local/rvm/gems/ruby-2.6.1/gems/learn-test-2.6.1/lib/learn_test/reporter.rb:13:in &#96;report'
         1: from /usr/local/rvm/gems/ruby-2.6.1/gems/learn-test-2.6.1/lib/learn_test/reporter.rb:47:in &#96;report'
/usr/local/rvm/gems/ruby-2.6.1/gems/learn-test-2.6.1/lib/learn_test/strategies/mocha.rb:42:in &#96;results': undefined method &#96;[]' for nil:NilClass (NoMethodError)
```

I was able to reproduce this with @BlythePollard.

**Comment by sgharms** [comment]
@ivalentine 

I can reproduce this issue in Learn IB IDE, but not in my local env.

I have a preliminary solution though: changing mocha dependency to  `"mocha": "^6.1.4"` and then re-running `yarn install` gets IB IDE working. I've added this as a PR #6. 

I'm going to flag @maxwellbenton to verify that change as a fix and we'll merge once validated.

**Comment by sgharms** [comment]
@maxwellbenton Can you verify my PR here. It's a major bump to package.json and I want to make sure it's not better to either:

1. Not specify and let some other application drag up the best mocha version it can find
2. It's OK to bump to a 6x from a 5x.

I think you've been closer to this recently and have an opinion. LMK if I've done the right thing.

**Comment by maxwellbenton** [comment]
Hey @sgharms,

The bump does seem to fix the error in the in IBIDE, but testing it locally, I am getting the test to work and it seems to finish testing fine, but an error is produced in mocha immediately after and hangs there until forced to stop:

```
	9: from /Users/flatironschool/.rvm/gems/ruby-2.6.1/bin/learn-test:23:in `<main>'
	8: from /Users/flatironschool/.rvm/gems/ruby-2.6.1/bin/learn-test:23:in `load'
	7: from /Users/flatironschool/.rvm/gems/ruby-2.6.1/gems/learn-test-2.6.1/bin/learn-test:68:in `<top (required)>'
	6: from /Users/flatironschool/.rvm/gems/ruby-2.6.1/gems/learn-test-2.6.1/lib/learn_test/runner.rb:20:in `run'
	5: from /Users/flatironschool/.rvm/gems/ruby-2.6.1/gems/learn-test-2.6.1/lib/learn_test/runner.rb:20:in `fork'
	4: from /Users/flatironschool/.rvm/gems/ruby-2.6.1/gems/learn-test-2.6.1/lib/learn_test/runner.rb:21:in `block in run'
	3: from /Users/flatironschool/.rvm/gems/ruby-2.6.1/gems/learn-test-2.6.1/lib/learn_test/runner.rb:44:in `report_and_clean'
	2: from /Users/flatironschool/.rvm/gems/ruby-2.6.1/gems/learn-test-2.6.1/lib/learn_test/reporter.rb:13:in `report'
	1: from /Users/flatironschool/.rvm/gems/ruby-2.6.1/gems/learn-test-2.6.1/lib/learn_test/reporter.rb:47:in `report'
/Users/flatironschool/.rvm/gems/ruby-2.6.1/gems/learn-test-2.6.1/lib/learn_test/strategies/mocha.rb:42:in `results': undefined method `[]' for nil:NilClass (NoMethodError)
```

Something is changing in the way that `learn` is reporting the results. If this script is added to the package.json file, it will test and produce `.results.json` correctly:

```
"scripts": {
    "test": "mocha -R mocha-multi --reporter-options spec=-,json=.results.json"
  },
```

On mocha ^5.2.0, this lab doesn't seem to produce `.results.json` at all. On ^6.1.4, it creates the file but does not populate it, leading to an error likely because the file is empty. This doesn't seem to be happening on other labs I test when bumping mocha.
